services:
  PriceeIO\Controller\Admin\SyncController:
    autowire: true
    autoconfigure: true

  PriceeIO\Service\SyncService:
      autowire: true
      autoconfigure: true

  PriceeIO\Service\ApiService:
      autowire: true
      autoconfigure: true
