services:
  Pricee\Controller\Admin\SyncController:
    autowire: true
    autoconfigure: true

  Pricee\Service\SyncService:
      autowire: true
      autoconfigure: true

  Pricee\Service\ApiService:
      autowire: true
      autoconfigure: true
